version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: easystock-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: easystock
      POSTGRES_PASSWORD: easystock_123
      POSTGRES_DB: easystock_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
